login: &login
  adapter: 'postgresql'
  username: 'admintools'
  password: '123456'
  host: 'localhost'
  port: 5432
  encoding: 'UTF8'

development:
  <<: *login
  database: 'admintools_development'

test:
  <<: *login
  database: 'admintools_test'

production:
  <<: *login
  database: 'admintools_production'