every_10m_schedule_event_job:
  #cron: "*/30 * * * *"
  every: 30s
  class: ScheduleEvent
  #args:
  description: “”

domain_jobs_ping:
  every: 10s
  class: DomainJobsPing
  #args:
  description: "send curl"

local_ping_job:
  every: 1m
  class: LocalPing
  description: "Ping local desktops for check available"

