every_10m_schedule_event_job:
  #cron: "*/30 * * * *"
  every: 30s
  class: ScheduleEvent
  #args:
  description: “”
ping_local_desktops:
  every: 10s
  class: ScheduleLocalPing
  #args:
  description: "Ping local desktops for check available"
domain_jobs_ping:
  every: 10s
  class: DomainJobsPing
  #args:
  description: "send curl"
