every_10m_schedule_event_job:
  #cron: "*/30 * * * *"
  every: 30s
  class: ScheduleEvent
  #args:
  description: “”
local_ping_job:
  every: 1m
  class: LocalPing
  description: "Ping local desktops for check available"