every_10m_schedule_event_job:
  #cron: "*/30 * * * *"
  every: 10m
  class: ScheduleEvent
  #args:
  description: “”

domain_jobs_ping:
  every: ['10m', first_in: '1s']
  class: DomainJobsPing
  #args:
  description: "send curl"

local_ping_job:
  every: ['10m', first_in: '1s']
  class: LocalPing
  description: "Ping local desktops for check available"